name: Terraform Multi-Env Pipeline

on:
  push:
    branches:
      - "**" # qualquer branch

  pull_request:
    branches:
      - develop
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 🔹 Define ambiente corretamente
      - name: Set environment
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          echo "Branch: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
          else
            echo "ENV=dev" >> $GITHUB_ENV
          fi

      # 🔐 AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 🐍 Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 📦 Instalar dependências (se tiver requirements.txt)
      - name: Install dependencies
        run: |
          if [ -f ../lambda/requirements.txt ]; then
            pip install -r ../lambda/requirements.txt
          fi

      # 🔍 Validar código Python
      - name: Lint Python
        run: |
          pip install flake8
          flake8 ../lambda --max-line-length=120

      # ▶️ Testar execução básica
      - name: Run Python script
        run: |
          python ../lambda/app.py

      # ⚙️ Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="key=${ENV}/lambda/terraform.tfstate"

      - name: Terraform Validate
        run: terraform validate

      # 🧪 SEMPRE roda plan
      - name: Terraform Plan
        run: terraform plan -var-file="envs/${ENV}.tfvars"

      # 🚀 APPLY apenas em develop ou main
      - name: Terraform Apply
        if: |
          github.event_name == 'push' &&
          (endsWith(github.ref, '/develop') || endsWith(github.ref, '/main'))
        run: terraform apply -auto-approve -var-file="envs/${ENV}.tfvars"
